vich_uploader:
    db_driver: orm
    mappings:
        articles:
            uri_prefix: /uploads
            upload_destination: "%kernel.project_dir%/public/uploads"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
